version: "2"
services:
  rtlamr_psql_collect:
    image: bpoetzschke/rtlamr_psql_collect:latest
    environment:
      DEBUG: true
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: db_user
      DB_PASSWORD: db_passwd
      DB_DATABASE: rtlamr
      RTLAMR_FILTERID: 12345,23456
    restart: unless-stopped