version: "3"
services:

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: rtlamr
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    restart: unless-stopped
    ports:
      - "5432:5432"